### ISSUE TITLE
I wish there was a similar library with MIT license

### ISSUE THREAD

**Issue by JenieX** [eight04/GM_config#2]
Using this, means we will have to change our MIT licensed user scripts to match the license of this library, which we will not do.

 I have read the [discussion](https://github.com/eight04/GM_config/issues/1) at GitHub, so I understand it wasn't your choice, still shame.

**Comment by eight04** [comment]
Try [GM_webextPref](https://github.com/eight04/GM_webextPref)

**Comment by JenieX** [comment]
That is great, will do that.
Been using some of your scripts for as long as I can remember, and find them super useful.
Like [Select text inside a link like Opera](https://greasyfork.org/en/scripts/789-select-text-inside-a-link-like-opera), and [Linky Square](https://greasyfork.org/en/scripts/18006-linky-square). So thank you for sharing your work.
